In [1]:
#Display “Hello World” in your output screen.
print("hello world")

hello world


In [4]:
#Get the input from the user and perform addition of two numbers.
a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
c=a+b
print("the sum:",c)

Enter a number:5
Enter a number:9
the sum: 14


In [5]:
#swap two variables without temp variable
a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
print("A=",a)
print("B=",b)
print("After swapping:")
a,b=b,a
print("A=",a)
print("B=",b)

Enter a number:6
Enter a number:8
A= 6
B= 8
After swapping:
A= 8
B= 6


In [6]:
#convert the entered kilometres ( Convertion  Factor= 0.621371)
a=int(input("enter km value: "))
miles=a*0.621371
print("the miles value is :  ", miles)


enter km value: 4
the miles value is :   2.485484


In [7]:
#check whether the given number is positive, negative or 0
a=int(input("enter number 1 : "))
if a>=0:
    print("the number is positive")
else:
    print(" the number is negative")

enter number 1 : 9
the number is positive


In [8]:
#verify that the given year is a leap year
a=int(input("enter year : "))
if a%4==0:
    if a%100==0:
        if a%400==0:
            print("the year is a leap year")
        else:
            print("the year is not a leap year")
    else:
        print("the year is a leap year")
else:
    print("the year is not a leap year")

enter year : 2024
the year is a leap year


In [10]:
#display the prime numbers within the given interval
a=int(input("Enter a start range:"))
b=int(input("Enter a end range:"))
c=0
if a==1:
    a=2
for i in range (a,b):
    c=0
    for j in range (2,i):       
        if i%j==0:
            c=1
    if c==0:
        print(i)

Enter a start range:1
Enter a end range:10
2
3
5
7


In [3]:
#display the Fibonacci sequence up to n-th term
n = int(input("Enter the number of terms: "))
a = 0
b = 1
if n <= 0:
    print("Invalid input!")
elif n == 1:
    print("Fibonacci sequence up to", n, "term:")
    print(a)
else:
    print("Fibonacci sequence up to", n, "terms:")
    print(a)
    print(b)
    for i in range(2, n):
        c = a + b
        print(c)
        a = b
        b = c


Enter the number of terms: 7
Fibonacci sequence up to 7 terms:
0
1
1
2
3
5
8


In [4]:
#check if the number is an Armstrong number or not
a=int(input("enter a three digit number  : "))#123
b=a//100#1
c=a%100
d=c//10#2
e=c%10#3
num=(b**3)+(d**3)+(e**3)
if num==a:
    print("the number is an armstrong number")
else :
    print("its not an armstrong number")

enter a three digit number  : 153
the number is an armstrong number


In [5]:
#Find the Sum of natural numbers up to n-th term
a=int(input("enter number : "))
b=0
for i in range (a+1):
    b=b+i
print(b)


enter number : 10
55


In [6]:
#Write a function called show_stars(rows). If rows are 5, it should print the following:
for i in range(1,6):
    print("*"*i)

*
**
***
****
*****


In [10]:
#Write a program to remove characters from a string starting from zero up to n and return a new string.
str = input("Enter a string: ")
n = int(input("Enter the number of characters to remove: "))
new_str = str[n:]
print("New string:", new_str)

Enter a string: my friend is a fool
Enter the number of characters to remove: 5
New string: iend is a fool


In [13]:
#Iterate the given list of numbers and print only those numbers which are divisible by 5
list=[]
n=int(input("enter the no.of number:"))
for i in range(n):
    i=int(input("enter the number:"))
    list.append(i)
for i in list:
    if( i%5!=0):
        list.remove(i)
print(list)    

enter the no.of number:5
enter the number:45
enter the number:14
enter the number:25
enter the number:40
enter the number:36
[45, 25, 40]


In [15]:
#Write a program to find how many times substring “Hi” appears in the given string.
g=input("enter a sentence : ")
list=g.split(' ')
n=len(list)
c=0
for i in range (n):
    if list[i]=='hi':
        c+=1
if c!=0:
    print("'hi' is present {} times".format(c))
else:
    print("'hi' is not present")
        

enter a sentence : hi mynj hihihi
'hi' is present 1 times


In [24]:
#Print the following pattern
for i in range(1,6):
    for j in range (i):
        print(i,end="")
    print(end="\n")

1
22
333
4444
55555


In [25]:
#Write a program to check if the given number is a palindrome number.
name=input("enter the name : ")
rev=name[::-1]
if name==rev:
    print("its a palindrome")
else :
    print("its not a palindrome")

enter the name : malayalam
its a palindrome


In [27]:
#Python program to interchange first and last elements in a list
list=[]
n=int(input("enter the number of elements:"))
for i in range(n):
    i=int(input("enter the numbers:"))
    list.append(i)
print(list) 
list[0],list[n-1]=list[n-1],list[0]
print(list)

enter the number of elements:3
enter the numbers45
enter the numbers67
enter the numbers90
[45, 67, 90]
[90, 67, 45]


In [3]:
#Python program to swap two elements in a list
n=int(input("enter the number of element:"))
list=[]
for i in range(n):
    a=int(input("enter the elements:"))
    list.append(a)
print(list) 
for i in range(n):
    print("index",i,"=",list[i])
m=int(input("enter the index value:"))
s=int(input("enter the index value:"))
list[m],list[s]=list[s],list[m]
print("the swapped list is:",list)

enter the number of element:5
enter the elements:5
enter the elements:8
enter the elements:7
enter the elements:6
enter the elements:3
[5, 8, 7, 6, 3]
index 0 = 5
index 1 = 8
index 2 = 7
index 3 = 6
index 4 = 3
enter the index value:4
enter the index value:0
the swapped list is: [3, 8, 7, 6, 5]


In [14]:
#Python | Ways to find length of list
list=[1,2,3,4,5,6,7,8,9,10]
print(list) 
n=len(list)
print("the no. of element is:",n)
#or
list=[1,2,3,4,5,6,7,8,9,10]
print(list) 
c=0
for i in list:
    c+=1
print("the no. of element is:",c)    

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
the no. of element is: 10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
the no. of element is: 10


In [16]:
#Maximum of two numbers in Python
a=int(input("enter the elements:"))
b=int(input("enter the elements:"))
max=max(a,b)
print("the maximum number is:",max)      

enter the elements:4
enter the elements:5
the maximum number is: 5


In [17]:
#Minimum of two numbers in Python
a=int(input("enter the elements:"))
b=int(input("enter the elements:"))
min=min(a,b)
print("the minimum number is:",min)      

enter the elements:45
enter the elements:67
the minimum number is: 45


In [37]:
#Python program to check whether the string is Symmetrical or Palindrome
a=input("enter the string:")
print(a)
half=int((len(a)/2))
first=a[:half]
last=a[half:]
x=last[::-1]
if(first==x):
    print("it is symmetrical")
else:
    print("it is not symmetrical")
b=a[::-1]
if(a==b):
    print("it is palindrome")
else:
    print("it is not palindrome")

enter the string:malayalam
malayalam
it is not symmetrical
it is palindrome


In [29]:
#Reverse words in a given String in Python
a=input("enter the string:")
b=''.join(reversed(a))
print(b)
if(a==b):
    print("it is palindrome")
else:
    print("it is not palindrome")

enter the string:malayalam
malayalam


In [43]:
#Ways to remove i’th character from string in Python
a=input("enter the string:")
b=int(input("enter the index value:"))
c=a[:b]+a[b+1:]
print(c)

enter the string:malayalam
enter the index value:3
malyalam


In [44]:
#Find length of a string in python 
a=input("enter the string:")
n=len(a)
print(n)

enter the string:hi hello
8


In [3]:
#Python program to print even length words in a string
a=input("enter the string:")
n=len(a)
b=a.split(" ")
for i in b:
    if(len(i)%2==0):
        print(i)

enter the string:hi hello everyone
hi
everyone


In [1]:
#Python program to Find the size of a Tuple
tuple=(2,4,8,16,32)
b=len(tuple)
print(b)    

5


In [5]:
#Python – Maximum and Minimum K elements in Tuple
t=(5,10,15,20,25)
print("Maximum value= ",max(t))
print("Minimum value= ",min(t)) 

Maximum value=  25
Minimum value=  5


In [6]:
#Python – Sum of tuple elements
my_tuple = (10, 20, 30, 40, 50)
total = 0
for element in my_tuple:
    total=total + element
print("Sum of tuple elements:", total)


Sum of tuple elements: 150


In [10]:
#Python – Row-wise element Addition in Tuple Matrix
matrix = ((2, 4, 8),
          (3, 9, 27),
          (4, 16, 64))
sums = []
for row in matrix:
    sum = 0
    for element in row:
        sum += element
    sums.append(sum)
print("Row-wise sums:",sums)


Row-wise sums: [14, 39, 84]


In [1]:
#31. Create a list of tuples from given list having number and its cube in each tuple.
def cubeoflist(li):
    result=[(num, num**3) for num in li]
    return result
li = [3, 4, 1, 2]
print(cubeoflist(li))

[(3, 27), (4, 64), (1, 1), (2, 8)]


In [2]:
#32.Python - Sort python dictionaries by key or value
myDict = {'ravi': 10, 'rajnish': 9,
        'sanjeev': 15, 'yash': 2, 'suraj': 32}
 
myKeys = list(myDict.keys())
myKeys.sort()
sorted_dict = {i: myDict[i] for i in myKeys}
 
print(sorted_dict)

{'rajnish': 9, 'ravi': 10, 'sanjeev': 15, 'suraj': 32, 'yash': 2}


In [3]:
#33. Python dictionary with keys having multiple values.
dic = {}

a,b,c= 5, 3, 10

p,q,r= 12, 6, 9
dic["x-y+z"] = [a-b+c,p-q+r]
print(dic)

{'x-y+z': [12, 15]}


In [4]:
#34. Python program to find the sum of all items in a dictionary.
dic={ 'x':455, 'y':223, 'z':300, 'p':908 }

print("Dictionary: ", dic)

#using sum() and values()
print("sum: ",sum(dic.values()))

Dictionary:  {'x': 455, 'y': 223, 'z': 300, 'p': 908}
sum:  1886


In [6]:
#35. Python program to find the size of a dictionary
import sys

def get_dictionary_size(dictionary):
    return sys.getsizeof(dictionary)
my_dict = {'key1': 100, 'key2': 200, 'key3': 300}
size = get_dictionary_size(my_dict)
print(f"The size of the dictionary is {size} bytes.")


The size of the dictionary is 232 bytes.


In [13]:
#36. Find the size of a set in Python
import sys
def get_set1_size(set):
    return sys.getsizeof(set1)
def get_set2_size(set):
    return sys.getsizeof(set2)
def get_set3_size(set):
    return sys.getsizeof(set3)
Set1 = {"A", 1, "B", 2, "C", 3}
Set2 = {"Geek1", "Raju", "Geek2", "Nikhil", "Geek3", "Deepanshu"}
Set3 = {(1, "Lion"), ( 2, "Tiger"), (3, "Fox")}
size = get_set_size(set)
print(f"The size of the set is {size} bytes.")
size = get_set_size(set)
print(f"The size of the set is {size} bytes.")
size = get_set_size(set)
print(f"The size of the set is {size} bytes.")

The size of the set is 408 bytes.
The size of the set is 408 bytes.
The size of the set is 408 bytes.


In [15]:
#37. Iterate over a set in Python
my_set = {1, 2, 3, 4, 5}
for element in my_set:
    print(element)

1
2
3
4
5


In [16]:
#38. Python- Maximum and minimum in a Set
def MAX(sets):
    return (max(sets))
sets=set([23,8,19,28,25,78,98,345,678,999])
print("The maximum element in the set is:",MAX(sets))
def MIN(sets):
    return(min(sets))
print("The minimum element in the set is:",MIN(sets))

The maximum element in the set is: 999
The minimum element in the set is: 8


In [18]:
#39. Python-Remove items from a set
languages={'Python','Java','English','C','C++','Tamil','Hindi'}
languages.remove('C')
print(languages)

{'English', 'C++', 'Java', 'Hindi', 'Tamil', 'Python'}


In [19]:
#40. Python-Check if two lists have atleast one element in common
def common_data(list1,list2):
    result=False
    for x in list1:
        for y in list2:
            if x==y:
                result=True
                return result
    return result
a=[1,2,3,4,5]
b=[5,6,7,8,9]
print(common_data(a,b))
a=[1,2,3,4,5]
b=[6,7,8,9]
print(common_data(a,b))

True
False


In [22]:
#41. Python-Assigning subsequent rows to matrix first row elements
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for i in range(1, len(matrix)):
    for j in range(len(matrix[i])):
        matrix[i][j] = matrix[0][j]
for row in matrix:
    print(row)


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [23]:
#42. Adding and Subtracting matrices in python
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[6,7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A,B))
print("Subtraction of two matrix")
print(np.subtract(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [24]:
#43. Python-Group similar elements into Matrix
from itertools import groupby
test_list=[1,3,5,1,3,2,5,4,2]
print("The original list:" +str(test_list))
res =[list(val) for key, val in groupby(sorted(test_list))]
print("Matrix after grouping:"+str(res))

The original list:[1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix after grouping:[[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [25]:
#44)Python – Row-wise element Addition in Tuple Matrix
test_list=[[('Gfg',3), ('is',3)], [('best',1)], [('for',5), ('geeks',1)]]
print("The original list is:"+ str(test_list))
cus_eles=[6,7,8]
res=[[sub+(cus_eles[idx],) for sub in val] for idx, val in enumerate(test_list)]
print("The matrix after row elements addition :"+str(res))

The original list is:[[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]
The matrix after row elements addition :[[('Gfg', 3, 6), ('is', 3, 6)], [('best', 1, 7)], [('for', 5, 8), ('geeks', 1, 8)]]


In [26]:
#45)Create an n x n square matrix, where all the sub-matrix has the sum of opposite corner elements as even
import itertools
def sub_mat_even(n):
    temp = itertools.count(1)
    l = [[next(temp)for i in range(n)]for i in range(n)]
    if n%2 == 0:
        for i in range(0,len(l)):
            if i%2 == 1:
                l[i][:] = l[i][::-1]
# Printing the array formed
    for i in range(n):
        for j in range(n):
            print(l[i][j],end=" ")
        print()
n = 4
sub_mat_even(n)

1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


In [27]:
#46)How to get list of parameters name from a function in Python?
import inspect
def fun(a, b):
    return a**b
print(inspect.signature(fun))

(a, b)


In [30]:
#47)How to Print Multiple Arguments in Python?
name = "John"
age = 30
city = "New York"

print(name, age, city)


John 30 New York


In [37]:
#48)Python program to find the power of a number using recursion
def power(base, exponent):
    if exponent == 0:
        return 1
    else:
        return base * power(base, exponent - 1)

base = 2
exponent = 3

result = power(base, exponent)
print(f"{base} raised to the power of {exponent} is: {result}")


2 raised to the power of 3 is: 8


In [1]:
#49)Sorting objects of user defined class in Python
class MyClass:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def __lt__(self, other):
        return self.age < other.age
obj1 = MyClass("John", 25)
obj2 = MyClass("Alice", 30)
obj3 = MyClass("Bob", 20)
my_list = [obj1, obj2, obj3]
sorted_list = sorted(my_list)
for obj in sorted_list:
    print(obj.name, obj.age)


Bob 20
John 25
Alice 30


In [2]:
#50)Functions that accept variable length key value pair as arguments
def process_data(**kwargs):
    for key, value in kwargs.items():
        print(key, value)
process_data(name="John", age=25, city="New York")


name John
age 25
city New York
